### ISSUE TITLE
Error at login : Failed opening required '../../service/v2/rest.php'

### ISSUE THREAD

**Issue by westmalle** [QuickCRM/QuickCRM-Basic#7]
Hi,

My configuration is SuiteCRM 7.10.7, PHP 7.0.31, Apache/2.4.34.
QuickCRM version 3.9.0
All permissions set up as required.
Stuck on login asking to check permissions ...
The error is : 
[Sun Aug 26 18:43:24.489174 2018] [:error] [pid 72] [client 78.228.69.59:41011] PHP Fatal error:  require_once(): Failed opening required '../../service/v2/rest.php' (include_path='.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/custom/QuickCRM/rest2.php on line 11
By searching in the service directory, I cannot see any 'v2' subfolder, so I imagine this is the issue.
Are the versions I use not compatible ?

Thanks,
P.

Content of the php script causing the error :

root@aedd532cac50:/bitnami/suitecrm# cat /bitnami/suitecrm/custom/QuickCRM/rest2.php 
...
 if(!defined('sugarEntry'))define('sugarEntry', true);
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Methods: POST,GET");
header("Access-Control-Allow-Credentials: true");
require_once('../../service/v2/rest.php');

**Comment by QuickCRM** [comment]
Hi,

Our module is compatible with all versions of  SuiteCRM (it's even compatible with old versions of SugarCRM CE). 
In the service directory, you are supposed to find v2, v3, v4 and v4_1. 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile

**Comment by QuickCRM** [comment]
This is github service directory for SuiteCRM version 7.10.7:
https://github.com/salesagility/SuiteCRM/tree/master/service

There is a v2 directory, so you might have a permissions or ownership error. 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile

**Comment by westmalle** [comment]
Thanks for the answer.
I'm confused about the service directory : There are 2 directories : 

/bitnami/suitecrm/service:
total 4
drwxrws--- 2 daemon daemon 4096 Aug 26 18:42 quickcrm

/opt/bitnami/suitecrm/service/:
total 40
drwxr-xr-x 2 root root 4096 Aug 15 06:05 JsonRPCServer
drwxr-xr-x 3 root root 4096 Aug 15 06:05 core
drwxr-xr-x 2 root root 4096 Aug 15 06:05 example
drwxr-xr-x 2 root root 4096 Aug 15 06:05 utils
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v2
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v2_1
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v3
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v3_1
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v4
drwxr-xr-x 2 root root 4096 Aug 15 06:05 v4_1

Is it a correct situation ?

**Comment by QuickCRM** [comment]
How did you install our module? 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile

**Comment by westmalle** [comment]
I used the suitecrm admin module loader.
If it can help, my suitecrm source is https://github.com/bitnami/bitnami-docker-suitecrm

**Comment by QuickCRM** [comment]
I don't understand why you have two suitecrm directories (/bitnami/suitecrm/service and /opt/bitnami/suitecrm/service) 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile
